### ISSUE TITLE
Bug: yarn install causing node-sass errors on lint

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#562]
When doing a node_modules install with yarn, something seems to be missing. Looks like there is a [known issue](https://github.com/sass/node-sass/issues/1387) about having to do `npm rebuild node-sass`, however, this is not required when installing using `npm install`.

## Steps for Reproducing

- install node modules with `yarn install`
- run `npm run lint`
- see error:

```
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/scottnath/development/gitrepos/punchcard-cms/punchcard/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/Users/scottnath/development/gitrepos/punchcard-cms/punchcard/node_modules/node-sass/lib/extensions.js:120:13)
    at foundBinariesList (/Users/scottnath/development/gitrepos/punchcard-cms/punchcard/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/scottnath/development/gitrepos/punchcard-cms/punchcard/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/scottnath/development/gitrepos/punchcard-cms/punchcard/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/scottnath/development/gitrepos/punchcard-cms/punchcard/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/scottnath/development/gitrepos/punchcard-cms/punchcard/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by Snugug** [comment]
Learnings from the yarn community as it's being consumed suggest it's really good for production projects, but not so great for node modules themselves. I'm OK removing it

**Comment by scottnath** [comment]
Will bring up in sprint planning. Do we need a story or is the bug report
good enough?

**Comment by Snugug** [comment]
This bug report's fine

**Comment by scottnath** [comment]
not to pass the buck...but I'm not sure of the extrication involved. Story
por vous?
